---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# BREAD

<!-- badges: start -->
<!-- badges: end -->

The goal of BREAD is to calculate kinship from SNP data. 

## Installation

You can install the development version of BREAD from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("jonotuke/BREAD")
```

## Example

This is a basic example which shows you how to solve a common problem:

First we load a basic counts example. 

```{r example}
library(BREAD)
counts_example
```

We can get the call of kin using

```{r}
relatedness_example <- callRelatedness(counts_example)
relatedness_example
```

```{r}
plotLOAF(relatedness_example)
```

```{r}
plotSLICE(relatedness_example, row = 1)
```

```{r, eval=FALSE}
saveSLICES(relatedness_example)
```

```{r}
test_degree(relatedness_example, 1, 1)
```



